DevelopmentConsumption Reporting - Generating the reportingClientId
5G-MAG/rt-5gms-media-stream-handler pull request #61
Opened 2023-11-24 06:32 UTC by shilinding

Identifier of the reporting client that consumed the streaming media service associated with this consumption report.
If available to the Media Session Handler, a GPSI value (see clause 28.8 of TS 23.003 [7]); otherwise, a stable and globally unique string.

when GPSI availabe, use GPSI; else, use UUID.

2023-11-24 08:30 UTC, dsilhavy requested changes
Thanks @shilinding . In addition to my comments please also merge the latest version of the `development` branch again as I merged some changes this morning.

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +    private fun getMSISDN(): String {
Add `@RequiresApi(Build.VERSION_CODES.TIRAMISU)` , `getPhoneNumber` is only available with Android API 33

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +    private fun genReportingClientId(): String
Add `   @RequiresApi(Build.VERSION_CODES.TIRAMISU)`

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +    private val reportingClientId = genReportingClientId()
Add `@RequiresApi(Build.VERSION_CODES.TIRAMISU)`

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +    @SuppressLint("Range")
Only use ` @SuppressLint("Range")` for functions which use ` Log.d(TAG)`

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +    private fun getMSISDN(): String {
Add this to all functions which are related to this.

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +            var subscriptionId = subscriptionInfo.getSubscriptionId()
Use `val`

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +            var subscriptionName: String = subscriptionInfo.getCarrierName() as String
Use `val`

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +        var simOPName: String = telephonyManager.getSimOperatorName()
Use `val`

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +            if (subscriptionInfoList != null) {
Condition 'subscriptionInfoList != null' is always 'true'

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +        var simOPName: String = telephonyManager.getSimOperatorName()
Use of getter method instead of property access syntax

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +            var subscriptionId = subscriptionInfo.getSubscriptionId()
Use of getter method instead of property access syntax

2023-11-24 08:30 UTC, dsilhavy commented on app/src/main/java/com/fivegmag/a5gmsmediastreamhandler/consumptionReporting/ConsumptionReportingController.kt
> +            var subscriptionName: String = subscriptionInfo.getCarrierName() as String
Use of getter method instead of property access syntax

2023-12-01 10:13 UTC, shilinding commented
> @shilinding Is this PR ready to be reviewed again? Did you incorporate all of my suggestions above?

Yes,  it's ready to be reviewed, all your suggestions are included in the last commit. Sorry I thought you'll see it when I submitted it, so I didn't give you another notice.

2023-12-06 10:06 UTC, merged